#+title: 2024-02-07
#+subtitle: A little bit of sci-fi

#+begin_verse
They're seldom things but brisk gusts' shrieks,
across a barren planet's planes.
Things that thought have been outcast.
Bleak scenes of solemn are all that last.

Bar a shadow, rippling on the sand
edging forward, an outstretched hand.
dragging onwards a dying man
always moving, to escape this land.

Leaks in past famed fision plants
had brought destruction; paved the world
with grit and grain, and nothing more.
Yet now this man, this intruder was
a living-thing come, a thing with cause.

--- 

That disruption fret the wind.
The crusade blast that killed all thing.
Now it spat and coughed and kicked,
into the man the grain and grit.

Rains of sand would on him fall;
the wind wished death and nothing more.
But exhausted it grew the more he crawled.
The man who moved; the man who thought.

---

Had he but not been long ago,
one with dreams and life and hope;
ambition scuffed with casual woes;
worries still, but he could cope.

Now hope was scarce,
dwindling fast to nil.
Hunger encroached,
and thirst was hell.

..but blisters:
these were mortal wounds!
he'd leave them here with the dunes!
This sand that shifted, and danced and changed.
His pain, like it, would disperse and fade

Moments stretched on into days,
He cursed all things; he cursed his name
Forever past, it tempted death
But after each chocked gasp, he took again a breath.

---

Until it seemed the air did change.
Gusts fell to drafts; a breeze of wind.
Strange settlings of hazard down to bliss,
brittle grains to earth: damp soil! He could kiss..

Relief struck him like a nuclear blast.
He dug deep his fingers, and cried, and laughed.
He took to his feet,
and with all loving strain, he proclaimed:
"These are my lands; they will bear my name!
This is my garden!
And all will begin again!"

#+end_verse
