#+title: /Incomplete/ A spacman came travelling...
#+begin_export html
<p class="subtitle">2024-02-29</p>
#+end_export

#+begin_quote
I've got some idea where I want this to go. Not enough though to make it fun to write without the kind of thinking you do when you're stuck and on a deadline. I'm not on a deadline; I do not mind when this is done. So, until I'm siezed by intrigue, this will stay here incomplete.
#+end_quote

#+begin_verse
A spaceman came travelling, some hero of a world bygone.
The flash dazed me from my home; I followed its path along
the pleated streak of spectral fire that announced his rite on earth.
As he emerged, bewildering me, in a starless night I searched.

Buried in his destructed craft, illuminated by light I shone,
lept from debris, he siezed my torch. We jostled before it tripped.
I was struck scared, cursered under my breath but settled me did his:
A friendly heat in the dark: offerings of amnisty. 

A spaceman came travelling, of a world beheld by death.
I craned my neck to inspect him as moonlight bloomed his breath.
Hunger had made his body frail, I saw he needed rest.
His desperation graced me; I took his weight and left.
#+end_verse

* COMMENT Notes

I caught him whisper weakly, to me a pleading ask:
To interject his story with frank ansawers of my own.
We had settled in my home and made fresh company.
With such desire to know his tale, I took my simple task.

A spaceman came travelling, to an earth long ago
He arrived at the late epoch of a jurrasic world.

# He eyed me with a gentle panic, brought from that world bygone. 
# He wronged my trust; he siezed my torch, lept out of perilous debris:

A raptor came to par

A hunk of flesh with tools of stone

A Pharoh on his throne.

An Athenian democrat

An exuberant royal heir

A peasant roted in a dark age of despair

A renaisance man, draped in vibrancy

A physicist of the 20th century.

Then he came to our monastry

I live about a massful orb
contorting time itself
I've watched worlds bloom and fall
I've come to learn the cause.

I prey on life of other worlds.

came for the harvest
what produce did we have to offer

...Aboard our station 
