#+title: The Summer Was Over
#+date: 2021-10-01

#+begin_comment

A first draft of course work for my English GCSE.

#+end_comment

The docks were all Chidi knew; he saw them as his home, however ironic that may be. After all, they were a base of His Majesty’s navy: certainly a home more grandiose than Chidi deserved. For that, he was grateful.

He took on factory work young; his mother needed care. Overhearing the doctor’s strong words, Chidi listened, startled: "Get your act together woman. For heaven’s sake you have a boy to look after." He was an incorrigible man, Chidi reflected. His mother need not look after him; he was not the subject of concern. That was his mother, who he took care of. Chidi never felt appreciated for this. As his mild infuriation peaked, his mother stormed out of the practice, dragging him with her.

Textiles were a dangerous occupation and Chidi well knew the stories: limbs severed, appendages removed, lives lost. Though, unlike the other boys, he was honoured to have his job. Today was a day he felt this especially. He would be spinning the navy blue threads of soon to be sailor’s uniforms. Later to be donned in bustling changing rooms; later to be paraded in prideful celebration.

The factory floor was a boisterous atmosphere: distractions loomed, luring the credulous. It was then the machines would strike. God’s children - drowned; the hum of production uninterrupted. Chidi took each case as a lesson. Only one was lost today: bled out in hiding. The foolish boy had damaged his station’s equipment, mangled his hand in its metal extremities. Fearing punishment, the child muffled his cries and hid while he contemplated his strategy. A decision was not made while he had the capacity to do so; Chidi watched as the pale-faced boy was carted out, his corpse having been discovered. This was Man’s Britain.

The night was cold and Chidi’s attire was limited. Only a few days prior, nightfall had scared him home, running to his mother’s arms. But tonight he chose to endure. Besides, he was too tired for anything beyond a brisk walk. En route, he passed three suited men sat drinking. This was an industrial complex. They were navy. Chidi beamed. The right-most man clambered to his feet, his eyes glaring through the boy that stood before him. "Bugger off, would you". He proceeded to hurl his bottle at the ground beneath Chidi who bounded backwards in response. Chuckling, the companions threw too in quick succession, warding off the child. Chidi laughed half-heatedly, scuttling away. He had expected somewhat more of a hospitable attitude from the sailors. Perhaps he had been fooling himself to think the docks were his home. Desperate to justify the men’s actions, he neglected the silhouette lurking amidst the complex.

Chidi stepped into the building beneath the dockyard’s semaphore tower. Ignorant to his feelings of betrayal, he felt a terrible wrench within. Clenching a banister, he carried his weight forward; he could not be seen to loiter. His whimpers left his senses impaired as smoke tailed him. The silent beast behind him lashed out, embers scorching the back of his neck. Chidi turned to meet the wall of flame chasing him. A scream ripped his attention back; a woman buckled in front of her child. Desperate, she concealed the matches now scattered across the ground. Out of her reach, a dropped Jerry Can lay. She looked up, welling with panic, begging for her son’s forgiveness. Chidi met his mother’s eyes. A blistering gasp engulfed the corridor as he turned, as he ran from her, as he burned.

To him reached out the arm of a woman consumed in exhaust, choking on her fumes.

/The Summer Was Over./
